image: ubuntu:latest
stages:
  - build
  - test
  - deploy
  - code_quality

code_quality:
  stage: code_quality
  variables:
    UPLOAD_QUALITY_REPORT: 'curl -X PUT -H "Authorization:Token $QSCORED_API_KEY" -H "repository-link: $CI_PROJECT_URL" +  -H "username: hr637632@dal.ca" -H "Content-Type: mulitpart/form-data" --url "https://qscored.com/api/upload/file.xml?is_open_access=false&version=$CI_PIPELINE_IID&project_name=group20" -F "file=@Designite_output/DesigniteAnalysis.xml"'

  before_script:
    - apt-get update
    - ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone
    - apt-get --yes --force-yes install wget curl maven git

  script:
    - wget -O DesigniteJava.jar https://www.dropbox.com/s/mwizkj8uhplz4x3/DesigniteJava.jar?dl=1
    - echo $CI_PROJECT_PATH
    - echo $PAT
#    - java -jar DesigniteJava.jar -ci -repo $CI_PROJECT_PATH -pat $PAT -host "git.cs.dal.ca"
    - java -jar DesigniteJava.jar -ci -repo courses/2022-winter/csci-5308/group20/ -pat $PAT -host "git.cs.dal.ca"
    - 'eval "$UPLOAD_QUALITY_REPORT"'
  only:
    refs:
      - test-app

maven-build-test:
  image: maven:3-jdk-11
  stage: build
  script:
    - mvn test
    - "mvn -Ptest install -B"
  only:
    refs:
      - test-app