stages:
  - build
  - test
  - deploy

maven-build:
  variables:
    GIT_CHECKOUT: "true"
  image: maven:3-jdk-11
  stage: build
  script: "mvn package -B"
  only:
    refs:
      - main
      - develop
      - test
      - merge_requests
      - feature-admin
      - feature-frontend
      - feature-backend

build:
  variables:
    GIT_CHECKOUT: "true"
  script:
    - mvn clean install
    - java -jar DesigniteJava.jar -ci -repo $GITHUB_REPOSITORY -pat ${{ secrets.PAT }} -k ${{ secrets.D_KEY }}
    - ls
    - curl -X PUT -H "Authorization:Token ${{ secrets.QSCORED_API_KEY }}" -H "repository-link:https://github.com/" + GITHUB_REPOSITORY -H "username: 'Your email'" -H "Content-Type: mulitpart/form-data" --url "https://qscored.com/api/upload/file.xml?is_open_access=off&version=$GITHUB_RUN_NUMBER&project_name='Project name'" -F "file=@Designite_output/DesigniteAnalysis.xml"
  tags:
    - linux
  stage: build


maven-test:
  image: maven:3-jdk-11
  stage: test
  script: "mvn test -B"
  only:
    refs:
      - main
      - develop
      - test
      - merge_requests
      - feature-admin
      - feature-frontend
      - feature-backend

deploy:
  stage: deploy
  image: ruby:latest
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=app-staff-scheduler --api-key=$HEROKU_API_KEY
  only:
    refs:
      - main

