stages:
  - build
  - test
  - deploy

maven-build:
  variables:
    GIT_CHECKOUT: "true"
  image: maven:3-jdk-11
  stage: build
  script: "mvn package -B"
  only:
    refs:
      - main
      - develop
      - test
      - merge_requests
      - feature-admin
      - feature-frontend
      - feature-backend

build:
  variables:
    GIT_CHECKOUT: "true"
  script:
    - mvn clean install
    - wget "https://www.designite-tools.com/static/download/DJE/DesigniteJava.jar"
    - java -jar DesigniteJava.jar -ci -repo 'group20' 
      ls
  tags:
    - linux
  stage: build


maven-test:
  image: maven:3-jdk-11
  stage: test
  script: "mvn test -B"
  only:
    refs:
      - main
      - develop
      - test
      - merge_requests
      - feature-admin
      - feature-frontend
      - feature-backend

deploy:
  stage: deploy
  image: ruby:latest
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=app-staff-scheduler --api-key=$HEROKU_API_KEY
  only:
    refs:
      - main

