image: ubuntu:latest
stages:
  - build
  - test
  - deploy
  - code_quality

code_quality:
  stage: code_quality
  variables:
    UPLOAD_QUALITY_REPORT: 'curl -X PUT -H "Authorization:Token $QSCORED_API_KEY" -H "repository-link: $CI_PROJECT_URL" +  -H "username: hr637632@dal.ca" -H "Content-Type: mulitpart/form-data" --url "https://qscored.com/api/upload/file.xml?is_open_access=false&version=$CI_PIPELINE_IID&project_name=group20" -F "file=@Designite_output/DesigniteAnalysis.xml"'

  before_script:
    - apt-get update
    - ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone
    - apt-get --yes --force-yes install wget curl maven git

  script:
    - wget -O DesigniteJava.jar https://www.dropbox.com/s/mwizkj8uhplz4x3/DesigniteJava.jar?dl=1
    - java -jar DesigniteJava.jar -ci -repo $CI_PROJECT_PATH -pat $PAT -host "git.cs.dal.ca/courses/2022-winter/"
    - 'eval "$UPLOAD_QUALITY_REPORT"'
  only:
    refs:
      - main

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn package -B"
  only:
    refs:
      - main
      - develop
      - test
      - merge_requests
      - feature-admin
      - feature-frontend
      - feature-backend

maven-test:
  image: maven:3-jdk-11
  stage: test
  script: "mvn test -B"
  only:
    refs:
      - main
      - develop
      - test
      - merge_requests
      - feature-admin
      - feature-frontend
      - feature-backend

deploy-prod:
  stage: deploy
  image: ruby:latest
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=app-staff-scheduler --api-key=$HEROKU_API_KEY
  only:
    refs:
      - main

deploy-dev:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=app-staff-scheduler-dev --api-key=$HEROKU_API_KEY
  only:
    refs:
      - develop
